var tocTab = new Array();var ir=0;
tocTab[ir++] = new Array ("1", "Apresenta&ccedil;&atilde;o", "apresentação.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2", "Vendas", "vendas.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.1", "Par&acirc;metros", "parâmetros.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.1.1", "Par&acirc;metros de Venda", "parametrosdevenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.1.2", "Par&acirc;metros de Venda por Fun&ccedil;&atilde;o", "parametrosdevendaporfuncao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.1.3", "Par&acirc;metros de Cliente", "paramcliente_u.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.1.4", "Par&acirc;metros de Auto Servi&ccedil;o", "parâmetrosdeautoserviço.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.1.5", "Par&acirc;metros da Transportadora", "param_transportadora.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.1.6", "Par&acirc;metros de EDI", "parametrosedi.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2", "Manuten&ccedil;&atilde;o", "manutenção.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.2.1", "SelfColor", "selfcolor.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.2.1.1", "Linhas", "linhatinta.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.1.2", "Montadoras", "montadoresformix.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.1.3", "Tradutor", "tradutortinta.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.1.4", "Cores Tintas Imobili&aacute;rias", "corestintasimobiliarias.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.1.5", "Cores Tintas Automotivas", "corestintasautomotivas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.1.6", "Consulta Automotiva", "consultaautomotiva.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.1.7", "Consulta Imobili&aacute;ria", "consultaimobiliaria.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.2", "Regi&atilde;o de Pre&ccedil;o de Venda", "cadastroderegiaodeprecodevenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.3", "Libera Cliente p/Desconto Adicional", "liberacaoclientevendadescto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.4", "Rota de Entrega", "rotadeentrega.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.5", "Gerente de Venda", "manutençãodegerentedevendas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.6", "Supervisor de Vendas", "cadastrodesupervisor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.7", "Entregador/Cobrador", "cobraentrega_u.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.8", "Vendedor", "vendedor_u.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.9", "Tipo Entrega", "tpodeentrega.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.10", "Autoriza&ccedil;&atilde;o Venda Conv&ecirc;nio", "autorizacaovendaconvenio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.11", "Territ&oacute;rios de Venda", "territoriosdevenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.12", "Regi&atilde;o &Aacute;rea de Venda", "cadastrodeareadevenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.13", "SubRegi&atilde;o &Aacute;rea de Venda", "subregiãoáreadevenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.14", "Rota de Venda", "rotavenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.15", "Meta de Roteiriza&ccedil;&atilde;o", "meta_roteirizacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.16", "Meta de Vendas", "metavenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.17", "Comiss&otilde;es por Faturamento", "comissõesporfaturamento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.18", "Comiss&otilde;es por Recebimento", "comissõesporrecebimento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.19", "Alterar Valor Digitado Pedido de Venda", "alterar_vlr_dig_u.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.20", "Motivo para Lan&ccedil;amento do Conhecimento", "manutençãodemotivoconhecimento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.21", "Meta de Vendas Semanal", "metavendasemanal.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.22", "Premia&ccedil;&atilde;o de Representantes", "premiacao_prepresentantes.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.23", "Condi&ccedil;&atilde;o de pagamento Por SubCategoria", "condpgtosubcategoria.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.24", "Objetivos de Vendas Semanal por Vendedor", "metavendasemanalvend.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.25", "Clientes Distribui&ccedil;&atilde;o", "clientesdistribuicao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.26", "Altera Vendedor de Cliente", "altvendcliente.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.2.27", "Condi&ccedil;&atilde;o de Pagto no Fabricante", "condiçãodepagtonofabricant.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3", "Movimenta&ccedil;&atilde;o", "movimentação.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.3.1", "Venda", "venda.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.3.1.1", "Pedido de Venda Compacto", "pedidovendacompacto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.1.2", "Pedido de Venda Balc&atilde;o", "pedidovenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.1.3", "Pedido de Bonifica&ccedil;&atilde;o Cliente Balc&atilde;o", "pedidodevendabonificacaobalcao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.1.4", "Pedido de Venda Expedi&ccedil;&atilde;o Individual", "pedidovendaexpedicaoindividual.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.1.5", "Pedido Bonifica&ccedil;&atilde;o Expedi&ccedil;&atilde;o Individual", "pedidobonificacaoexpedicaoindi.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.1.6", "Gera&ccedil;&atilde;o Nota Fiscal Varejo", "geracaonotafiscalvarejo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.1.7", "Gera&ccedil;&atilde;o Nota Fiscal Expedi&ccedil;&atilde;o Individual", "geracaonfexpedicaoindividual.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.1.8", "Gera&ccedil;&atilde;o Nota Fiscal Venda Futura", "geranfvendafutura.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.2", "Venda Atacado", "vendaatacado.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.3.2.1", "Pedido de Venda Televendas", "pedidodevendatelevendas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.2.2", "Pedido de Bonifica&ccedil;&atilde;o Cliente Televendas", "pedidodevendabonificacaote.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.2.3", "Pedido de Consigna&ccedil;&atilde;o de Cliente", "sequencia_help_23.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.2.4", "Montagem de Cargas", "montagemdecarga.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.2.5", "Mapa de Separa&ccedil;&atilde;o por Carga", "mapadeseparacaoporcarga.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.2.6", "Clientes por Carga", "clientesporcarga.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.2.7", "Gera&ccedil;&atilde;o Nota Fiscal Atacado", "geracaonotafiscalatacado.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.2.8", "Impress&atilde;o de Documentos da Carga", "impressaodedocumentosdacarga.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.2.9", "Romaneio de Cargas", "romaneiodecargas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.2.10", "Consulta Produtos na Carga", "prodcarga.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.2.11", "Rateio de Carga", "rateiocarga.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.3", "Cancelamento NF Saida", "cancelamentonfsaida.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.3.3.1", "Cancela Nota Fiscal", "cancelanotafiscal.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.3.2", "Confirma Cancelamento da NF Caixa", "cancelanotafiscalcaixa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.3.3", "Confirma Cancelamento de NF Expedi&ccedil;&atilde;o", "cancelanotafiscalexpedicao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.4", "Entregas", "entregas.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.3.4.1", "Controle de Entregas", "controledeentregas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.4.2", "Comissao Entregador", "relatorioentrega.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.4.3", "Tipo de Ocorrencia", "ocorrenciaentrega.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.5", "Transferencia de Dados", "transferenciadedados.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.3.5.1", "Transfer&ecirc;ncia EDI", "transferenciaedi.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.5.2", "Gera&ccedil;&atilde;o For&ccedil;a de Vendas Blink", "forcavendasblink.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.5.3", "Importa&ccedil;&atilde;o For&ccedil;a de Vendas Blink", "importaçãoforçadevendasbli.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.5.4", "Notas Fiscais para Transportadoras", "movtonftransportadora.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.5.5", "For&ccedil;a de Vendas Next Solution", "forcavendasnextsolution.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.5.6", "Importa&ccedil;&atilde;o For&ccedil;a de Vendas Next Solution", "importacaofvnextsolution.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.5.7", "Gera&ccedil;ao For&ccedil;a de Vendas", "forcavendas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.5.8", "Importa&ccedil;ao For&ccedil;a de Vendas", "importacaoforcavendas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.5.9", "Gera&ccedil;&atilde;o For&ccedil;a de Vendas Kraft", "forcavendaskraft.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.5.10", "Gera&ccedil;ao For&ccedil;a Vendas Agrovicultor", "forcavendasagro.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.6", "Venda Fora do Estabelecimento", "vendaforadoestabelecimento.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.3.6.1", "Gera NF Saida p/ Transito de Mercadoria", "vendaforaestab.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.6.2", "Mapa de Separacao", "mapaseparacaovfe.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.6.3", "Retorno de Venda fora do Estabelecimento", "retornovfe.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.6.4", "Critica e Atualiza&ccedil;&atilde;o de VFE", "atuvfe.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.7", "Atendimento Parcial de Pedido de Venda", "sequencia_help_20.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.8", "Atendimento de Venda por Encomenda", "atendimentodevendaporencomenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.9", "Estorno Atendimento Parcial Pedido Venda", "sequencia_help_36.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.10", "Consulta Notas Fiscais", "consultanotasfiscais.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.11", "Indeniza&ccedil;&atilde;o", "indenização.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.12", "Retorno de Consigna&ccedil;&atilde;o Cliente", "consignacaoclienteporcarga.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.13", "Outras Sa&iacute;das", "outrassaidas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.14", "Libera&ccedil;&atilde;o de Pedido de Venda", "liberacao_pedido_venda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.15", "Conhecimento de Frete", "conhecimentodefretesaidas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.16", "Altera&ccedil;&atilde;o Comiss&otilde;es por N&iacute;vel Desconto", "alteraçãodecomissões.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.17", "Altera&ccedil;&atilde;o de Comiss&otilde;es do Vendedor", "alteraçãodecomissõesdovendedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.18", "Cancelamento de Devolu&ccedil;&atilde;o de Venda", "cancelamento_devolucao_cliente.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.19", "Movimenta&ccedil;&atilde;o Conta Corrente Vendedores", "movicontavendedores.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.20", "Gera&ccedil;&atilde;o de NF de Venda Especial", "vendaespecial.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.21", "Listagem de Pedidos Liberados", "listagemdepedidosliberados.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.3.22", "Altera&ccedil;&atilde;o do Vendedor do Pedido", "alteraçãodovendedordopedid.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4", "Relat&oacute;rios", "relatórios.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.4.1", "Roteiriza&ccedil;&atilde;o", "roteirização.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.4.1.1", "An&aacute;lise de Clientes", "relanaliseclientes.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.1.2", "Mix por &Aacute;rea", "relatoriodemixporarea.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.1.3", "Acompanhamento de Metas", "acompanhamentometas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.2", "Relat&oacute;rios Administrativos", "relatóriosadministrativos.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("2.4.2.1", "Linha de Produto por Cidade", "relatóriodepartamentoporcid.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.2.2", "Linha de Produto por RCA", "relatóriodepartamentoporven.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.2.3", "Linha de Produto por RCA/Margem", "relatóriodelinhaporrca.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.2.4", "Estoque Financeiro por Fornecedor", "estoquefinanceiroporfornece.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.2.5", "Desempenho de Vendas", "relatóriodedesempenhodeven.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.3", "Reemiss&atilde;o de Nota Fiscal", "nota_fiscal.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.4", "Impress&atilde;o de Notas Fiscais n&atilde;o Impressas", "nf_nao_impressa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.5", "Emiss&atilde;o de Nota Fiscal a partir do Cupom", "geranfdecupom.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.6", "Curva ABC", "curva_abc.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.7", "Comiss&atilde;o de Vendas", "comissaovendas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.8", "Reemiss&atilde;o de Mapa de Separa&ccedil;&atilde;o", "reemissãodemapadeseparação.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.9", "Impress&atilde;o de Mapas n&atilde;o Impressos", "impressãodemapasnãoimpressos.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.10", "Consigna&ccedil;&atilde;o de Carga em Aberto", "consignacaocargaaberto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.11", "Comprovante Venda Futura Imediata", "comprovantevendafuturaimediata.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.12", "Relat&oacute;rio de Fechamento de Caixa Varejo", "relatorio_fechamento_caixa_var.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.13", "Relatorio Resultado de Vendas", "relatorio_resultado_vendas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.14", "Campanha de Vendas", "promocoes.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.15", "Produtos Vendidos", "produtosvendidosporfornecedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.16", "Rela&ccedil;&atilde;o de Meta de Vendas", "relatoriometavenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.17", "Minuta de Despacho", "minutadespacho.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.18", "Rela&ccedil;&atilde;o de Pedidos Reservados", "relaçãodepedidosreservados.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.19", "Comiss&otilde;es por Nivel de Desconto", "relatoriodecomissoes.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.20", "Relat&oacute;rios de Indeniza&ccedil;&atilde;o", "relatorio_indenizacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.21", "Pedidos por Vendedor", "relpedidovendedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.22", "Clientes por Regiao/Status", "relclientestatus.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.23", "Pedidos de Venda", "relpedidovenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.24", "Resumo de Faturamento por Vendedor", "resumovendedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.25", "Vendas Geral por Fabricante", "relatoriogeraldevendaspor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.26", "Pedido Adicional", "pedido_adicional.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.27", "Rela&ccedil;&atilde;o de Notas Fiscais", "relnotafiscal.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.28", "Rela&ccedil;&atilde;o de Pedidos a Liberar", "relaçãodepedidosaliberar.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.29", "Relat&oacute;rio de Montagem de Cargas", "relmontagemcargas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.30", "Relat&oacute;rio de Pedidos de Venda (Completo)", "relpedidovendacomp.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.31", "Resumo de Pedidos a Faturar por Vendedor", "resumopedidosfaturar.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.32", "Pedido Adicional Wacco", "pedidoadicionalwacco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.33", "Clientes por Vendedor", "clientesporvendedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.34", "Relat&oacute;rio de Meta de Vendas Semanal", "relmetavendasemanal.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.35", "Pedidos a Faturar por Fabricante", "relpedidovendafabricante.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.36", "Resumo das Vendas por Forma de Pagamento", "relvendasformapgto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.37", "Relat&oacute;rio de Venda por Itens", "relatoriodevendaporitens.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.38", "Acompanhamento Di&aacute;rio de Vendas", "acompanhamentodiariodevendas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.39", "Acompanhamento de Metas de Venda", "acompanhamentodemetasdevenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.40", "Venda e Devolu&ccedil;&atilde;o por Fabricante", "relvendadevolucaofabricante.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.41", "Vendas X Recebimento", "vendasxrecebimento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.42", "Proje&ccedil;&atilde;o de Vendas", "projvenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.43", "Etiqueta dos Produtos da Nota Fiscal", "etiquetaprodutonf.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.44", "Produtos Vendidos de Outras Unidade Empr", "estretirado.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.45", "Etiqueta dos Produtos para Despacho", "etiquetaprodutodespacho.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.46", "Pedidos por Vendedor (Wacco)", "relpedidovendedorwacco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.47", "Vendas por Embalagem de Movimenta&ccedil;&atilde;o", "vendaembmov.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.48", "Comiss&atilde;o por Promotor", "comissaopromotor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.49", "Resumo Comiss&otilde;es por N&iacute;vel de Desconto", "resumodecomisssoesdesconto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.50", "Relat&oacute;rio de Comiss&otilde;es por Recebimento", "relatoriodecomissoesporrec.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.51", "Relat&oacute;rio de Notas sem Minuta", "notassemminuta.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.52", "Comissao Supervisor/Vendedor/Cliente", "comissaocliente.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.53", "Contas Correntes dos Vendedores", "contascorrentesvendedores.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.54", "Produtos cortados pelo Rateio de Carga", "produtoscortadosrateiocarga.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.55", "Relatorio de Vendas por Unidade Produto", "vendunidprod.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.56", "Comiss&atilde;o Transportadora", "comissaodetransportadora.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.57", "Relat&oacute;rio Vendas Intervalo Produto", "vendasintervaloproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.58", "Vendas/Indeniza&ccedil;&atilde;o", "relatoriovendasindenizacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.59", "Movimenta&ccedil;&atilde;o Conta Corrente Vendedores", "relmovimentacaocontavend.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.60", "Relatorio de Clientes Inativos", "relatoriodeclientesinativos.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.61", "Espelho do Pedido", "espelhopedido.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.62", "Acompanhamento de Pedidos por Atendente", "acompanhamentoatendente.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.63", "Relat&oacute;rio de Pre&ccedil;o M&eacute;dio Vendido", "precomediovendido.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.64", "Melhores Clientes p/ Per&iacute;odo", "vendacliente.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.65", "Acompanhamento de Venda Futura/Encomenda", "acompanhamentovndfuturaenco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.66", "Resumo Vendas Empresa", "resumovendasempresa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.67", "Pedidos de Entregas / Retirada", "pedidosentregaretirada.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.68", "Relat&oacute;rio de Cargas Pendentes", "relcargaspendentes.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.69", "Relat&oacute;rio de Seguro de Cargas", "relsegurocargas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.70", "Relat&oacute;rio de Conferente de Cargas", "conferentecarga.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("2.4.71", "Relat&oacute;rio de Entrega - Venda Atacado", "relatoriodeentregavendaata.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4", "Compras", "compras.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("4.1", "Par&acirc;metros", "parâmetros.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("4.1.1", "Par&acirc;metros de Compra", "cadastrodosparametrosdecompras.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.1.2", "Par&acirc;metros de Compra por Fun&ccedil;&atilde;o", "parametrodecompraporfuncao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.1.3", "Par&acirc;metros de Fornecedor", "parametrosdefornecedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.2", "Manuten&ccedil;&atilde;o", "manutenção.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("4.2.1", "Comprador", "cadastrodecomprador.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.2.2", "Concorrente", "concorrente.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.2.3", "Or&ccedil;amento de Compra / M&ecirc;s", "orcamentodecompra.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.2.4", "Cadastro de Embalagem de Compra", "embalagem_compraporproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3", "Movimenta&ccedil;&atilde;o", "movimentação.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("4.3.1", "Pre&ccedil;o Concorrente", "preco_concor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3.2", "Pre&ccedil;o de Tabela de Fornecedor", "preco_tabela_fornecedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3.3", "Contrato de Compra", "contratodecompra.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3.4", "Requisi&ccedil;&atilde;o de Compra", "sugestaodecompra.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3.5", "Cota&ccedil;&atilde;o de Produto", "cotaçãodeproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3.6", "Pedido de Compra", "pedidodecompracomcontrato.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3.7", "Pedido de Compra - Sint&eacute;tico", "pedidodecomprasintetico.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3.8", "Pedido de Compra - Bonifica&ccedil;&atilde;o", "pedidodecompra_bonificação.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3.9", "Libera&ccedil;&atilde;o de Pedido de Compra", "liberapedidodecompra.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3.10", "Consulta Pedido de Compra", "consultapedidodecompra.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3.11", "Consulta Tabela de Fornecedor", "consultatabeladefornecedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3.12", "Consulta Itens por Fornecedor", "consultaitensporfornecedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.3.13", "Consulta Requisi&ccedil;&atilde;o de Compra", "consultarequisiçãodecompra.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4", "Relat&oacute;rios", "relatórios.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("4.4.1", "Relat&oacute;rio de Estoque Excedente", "relestoque_excedente.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.2", "Relat&oacute;rio de Sugest&atilde;o de Compra", "relsugestaocompra.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.3", "Relat&oacute;rio de Sugest&atilde;o Compra/Calend&aacute;rio", "sequencia_help_27.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.4", "Relat&oacute;rio de Sugest&atilde;o de Compra - Unibom", "relatoriosugestaocompraunibom.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.5", "Relat&oacute;rio de Pedido de Compra", "relatóriodepedidodecompra.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.6", "Relatorio de Giro de Estoque", "relatoriodegirodeestoque.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.7", "Relat&oacute;rio de Itens por Fornecedor", "relatoriodeitensporfornecedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.8", "Itens no Estoque por Categoria", "rel_itensestoquecat.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.9", "Relat&oacute;rio de Bonifica&ccedil;&atilde;o", "relatóriodebonificação.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.10", "Relat&oacute;rio de Itens Sem Giro", "relitenssemgiro.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.11", "Relat&oacute;rio de Estoque M&iacute;nimo", "relatóriodeestoquemínimo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.12", "Reemiss&atilde;o de Pedido de Compra", "reemissãodepedidodecompra.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.13", "Relat&oacute;rio de Pre&ccedil;os (Concorr&ecirc;ncia)", "rel_concorrencia.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.14", "Hist&oacute;rico Libera&ccedil;&atilde;o de Pedido Compra", "liberacaopedidocompra.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.15", "Relat&oacute;rio de Cota&ccedil;&atilde;o por Per&iacute;odo", "relcustomizacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.16", "Relat&oacute;rio de Pedidos de Compra Wacco", "sequencia_help_33.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.17", "Relat&oacute;rio de Sugest&atilde;o de Compras Wacco", "sequencia_help_34.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.18", "Relat&oacute;rio de Sugest&atilde;o de Compras Teles", "sequencia_help_44.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("4.4.19", "Relat&oacute;rio de Sugest&atilde;o de Compras Suporte", "sequencia_help_54.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6", "Estoque", "estoque.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.1", "Par&acirc;metros", "parâmetros.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.1.1", "Par&acirc;metros de Estoque", "cadastrodeparametrosdeestoque.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.1.2", "Par&acirc;metros de Produto", "paramproduto_u.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2", "Manuten&ccedil;&atilde;o", "manutenção.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.2.1", "Departamento de Produto", "cadastrodedepartamento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.2", "Se&ccedil;&atilde;o de Produto", "cadastrodesecao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.3", "Categoria de Produto", "cadastrodecategoria.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.4", "Subcategoria de Produto", "cadastrodesubcategoria.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.5", "Unidade de Produto", "cadastrodaunidadedeproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.6", "Situa&ccedil;&atilde;o do Produto", "cadastrodasituacaodoproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.7", "Similares ou Id&ecirc;nticos", "gruposimilaridentico.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.8", "Conferente", "conferente_u.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.9", "Grupo de Pre&ccedil;o", "grupodepreco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.10", "Produto", "produto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.11", "Altera Fabricante Produto", "alterafabricanteprodutos.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.12", "Altera Sub-Categoria de Produto", "alterasubcategoria.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.13", "Tipo de Movimenta&ccedil;&atilde;o", "cadastrodostiposdemovimentacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.14", "Mensagem produto na Nota Fiscal", "mensagem_u.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.15", "Fabricante", "fabricante.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.16", "Certificado", "certificadodoproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.17", "Cadastro de Cores", "cores.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.18", "Cadastro de Cores do Fabricante", "coresfabricante.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.19", "Cadastro de Marcas", "marcas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.20", "Cadastro de Referencia Lote", "referencialote.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.21", "Altera Dados do Produto", "sequencia_help_77.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.22", "Log&iacute;stica", "logística.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.2.22.1", "Aloca&ccedil;&atilde;o", "alocação.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.22.2", "Aloca&ccedil;&atilde;o Produto", "alocaçãoproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.22.3", "Propriedade de Armazenamento", "propriedadedearmazenamento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.22.4", "Filtro de Propriedade por Palete", "filtrodepropriedadeporpale.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.22.5", "Norma de Paletiza&ccedil;&atilde;o", "normadepaletização.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.22.6", "Alocac&atilde;o de Produto em Palete", "alocacãodeprodutoempalete.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.22.7", "Mapa de Alocacao de Produtos / Setor", "mapadealocacaodeprodutos.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.22.8", "Mapa de Abastecimento Ponto de Apanho", "mapadeabastecimentopontode.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.22.9", "Reemiss&atilde;o de Etiqueta de Aloca&ccedil;&atilde;o", "reemissãodeetiquetadealoca.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.23", "Relat&oacute;rios", "relatórios2.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.2.23.1", "Produto", "produto2.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.23.2", "Departamento", "departamento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.2.23.3", "Grupo Similar ou Id&ecirc;ntico", "gruposimilarouidêntico.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3", "Movimenta&ccedil;&atilde;o", "movimentação.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.3.1", "Consulta de Notas Fiscais", "consultanotasfiscais.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.2", "Conhecimento de Frete", "conhecimentodefrete.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.3.2.1", "Lan&ccedil;amento", "lancamento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.3", "Entrada de Mercadorias", "entradademercadorias.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.3.3.1", "Lan&ccedil;ar Nota Fiscal", "lancarnotafiscal.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.4", "Outras Entradas", "outrasentradas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.5", "Devolu&ccedil;&atilde;o de Mercadorias", "devoluçãodemercadorias.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.3.5.1", "Devolu&ccedil;&atilde;o de Compra por Ordem Cega", "devolucaodecompraporordemcega.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.5.2", "Devolu&ccedil;&atilde;o de Compra", "devolucaodecompra.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.6", "Cancelar Entrada de Mercadoria", "cancelarentradademercadoria.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.7", "Acertos de Estoque", "acertosdeestoque.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.3.7.1", "Suspens&atilde;o Venda para Contagem", "suspensaovendaparacontagem.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.7.2", "Acerto de Estoque", "acertodeestoque.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.7.3", "Entrada/Sa&iacute;da de Estoque Manual", "entradasaidadeestoquemanual.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.8", "Entrada Cega", "entradacega.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.3.8.1", "Gerar Ordem Cega", "gerarordem.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.8.2", "Lancar Ordem Cega", "lancarordem.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.9", "Consulta produto", "consultaproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.10", "Troca de Mercadorias", "trocaproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.11", "Ficha de Estoque de Produto", "fichadeestoquedeproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.12", "Consulta Saldo de Estoque", "consultasaldodeestoque.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.13", "Cancelamento de Devolu&ccedil;&atilde;o de Compras", "sequencia_help_29.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.14", "Estornos da Devolu&ccedil;&atilde;o Venda", "estornosdadevoluçãovenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.3.15", "Troca Situa&ccedil;&atilde;o do Produto", "situaçãoproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4", "Relat&oacute;rios", "relatórios.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.4.1", "Estoques de Produto", "estoquesdeproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.2", "Relat&oacute;rio de Produtos Conjuntos", "relatóriosdeprodutosconjunto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.3", "Estoques de Produto por Etapa", "estoquesdeprodutoporetapa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.4", "Ordem de pagamento a fornecedor", "ordemdepagamentoafornecedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.5", "Estoque Desconto Adicional", "sequencia_help_62.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.6", "Etiqueta Produto", "emissao_etiq_cod_barra.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.7", "Entrada de Mercadorias por Per&iacute;odo", "sequencia_help_7.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.8", "Relat&oacute;rio de Fretes por Per&iacute;odo", "relatóriodefretesporperíodo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.9", "Historico por produto", "historicoproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.10", "Posicao de Estoque", "posicaoestoqueminuta.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.11", "Relat&oacute;rio de Acerto de Estoque", "relacertoestoque.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.12", "Produto sem Pre&ccedil;o de Venda", "produtosempreçodevenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.13", "Relat&oacute;rio de Saldo de Estoque", "relatoriodesaldodeestoque.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.14", "Relat&oacute;rio de Indeniza&ccedil;&atilde;o no Estoque", "rel_indenizacaoestoque.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.15", "Produtos em Garantia (Troca)", "produtotrocagarantia.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.16", "Relat&oacute;rio de Itens sem Entrada", "relitenssementrada.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.17", "Abastecimento do Deposito", "sequencia_help_38.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.4.18", "Relat&oacute;rio Produtos Lote M&aacute;ximo", "produtolotemaximo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.5", "Abastecimento de Lojas", "abastecimentodelojas.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("6.5.1", "Pedido", "pedidoabastecimento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.5.2", "Consultas", "consultaabastecimento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.5.3", "Altera Estoque Regulador", "alteraestoqueregulador.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.5.4", "Montagem de Carga", "montagemcargaabast.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.5.5", "Mapa de Separacao", "mapaseparacaoabast.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.5.6", "Processa Estoque", "processaestoqueabast.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.5.7", "Gera Nota Fiscal", "geranfabastecimento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.5.8", "Gera Senha para Entrada de Mercadorias", "senhanfabast.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("6.5.9", "Entrada de Mercadoria", "entranota.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8", "Pre&ccedil;os", "", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("8.1", "Parametros", "parametrosprecos.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("8.1.1", "Par&acirc;metros Pre&ccedil;o de Venda", "parametrosprecodevenda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.1.2", "Ajuste de Pre&ccedil;o por Subcategoria(Kilo)", "alteraprecokilo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.2", "Manutencao", "manutencaoprecos.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("8.2.1", "Tabela de Pre&ccedil;o", "tabela_preco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.2.2", "Pre&ccedil;o de Custo / Venda", "atualizatabelaauxiliar.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.2.3", "Ajuste de Precos / MarkUp", "ajustedeprecosmarkup.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.2.4", "Ajuste de Pre&ccedil;o Exce&ccedil;&atilde;o Produto", "ajustedepreçoexceçãoprodut.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.3", "Movimentacao", "movimentacaoprecos.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("8.3.1", "Margem de Lucro por Produto", "margem_u.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.3.2", "Administra&ccedil;&atilde;o de Pre&ccedil;os", "admpreco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.3.3", "Atualizar Preco de Tabela", "atualizarprecodetabela.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.3.4", "Ajuste de Pre&ccedil;o Coletivo", "ajustedepreçocoletivo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.3.5", "Gerar Livro Pre&ccedil;o", "geralivropreco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.3.6", "Consulta Tabela de Precos", "consultatabeladeprecos.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.3.7", "Consulta Pre&ccedil;os de Venda", "consultaprecoprodutossintetico.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.3.8", "Consulta Pre&ccedil;os por Cond Pgto", "consultapreçosporcond_pagto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.3.9", "Gera Tabela de Pre&ccedil;o Auxiliar", "geratabelapreco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.3.10", "Atualiza Tabela de Pre&ccedil;o", "atualizatabeladepreçogeral.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.3.11", "Atualiza Tabela de Pre&ccedil;o Vigente", "atualizatabelaprecoauxiliar.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.3.12", "Altera&ccedil;&atilde;o de Pre&ccedil;o por Grupo de Pre&ccedil;o", "sequencia_help_41.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.4", "Relatorios", "relatoriosprecos.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("8.4.1", "Emiss&atilde;o do Livro de Pre&ccedil;o", "emissaodolivrodepreco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("8.4.2", "Lista de Pre&ccedil;os por Per&iacute;odo", "rellistapreco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10", "Financeiro", "financeiro.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.1", "Parametros", "parametros.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.1.1", "Par&acirc;metros da Corpora&ccedil;&atilde;o", "parametrosdacorporacaodofi.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.1.2", "Par&acirc;metros Unidade Empresarial", "paramfinunempresarial_d.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.1.3", "Par&acirc;metros Unidade Empresarial Fun&ccedil;&atilde;o", "parametrosunidadeeempresarial.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.1.4", "Par&acirc;metros Malote", "parametrosmalote.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.2", "Manuten&ccedil;&atilde;o", "manutenção.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.2.1", "Banco", "cadastrodebanco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.2.2", "Classifica&ccedil;&atilde;o Aplica&ccedil;&atilde;o", "classifaplicacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.2.3", "Aplica&ccedil;&atilde;o", "aplicacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.2.4", "Caixa", "cadastrodecaixa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.2.5", "Conta Corrente", "cadastrodecontacorrente.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.2.6", "Al&iacute;nea Cheque Devolvido", "manutencao_alinea_ch_devolvido.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.2.7", "Instru&ccedil;&atilde;o Banco", "instrucao_interna.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.2.8", "Taxas Cond. Pagto por Administradora", "condicaopagtoadminsitradora.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.2.9", "Folhas de Cheque", "cadastrodefolhasdecheque.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.2.10", "Fonte de Informa&ccedil;&atilde;o Rendimento Aplica&ccedil;&atilde;o", "fonteinformacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3", "Movimenta&ccedil;&atilde;o", "movimentação.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.3.1", "Contas a Receber", "contasareceber.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.3.1.1", "Contrato de Financeiras", "contratofinanceiroreceber.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.2", "Fatura a Receber", "faturaareceber.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.3", "Gera Arquivo SCI/Equifax", "geracaoarquivosci.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.4", "Provisao de Faturas a receber", "provisaofaturasreceber.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.5", "Efetiva Provis&atilde;o de Fatura a Receber", "efetivaprovisaorecebimento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.6", "Recebimento T&iacute;tulos", "recebimentotítulos.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.7", "Estorno de Titulo", "estornotituloreceber.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.8", "Acerto de Carga", "acertodecargabaixatitulo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.9", "Ficha Financeira", "fichafinanceiracliente.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.10", "Aceite de T&iacute;tulo", "aceitedetitulos.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.11", "Renegocia&ccedil;&atilde;o de Titulo", "renegociacaodetitulo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.12", "Parcelamento de T&iacute;tulo", "parcelamentodetitulo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.13", "Recebimento de Cart&atilde;o de Credito", "recebimentodecartãodecredito.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.14", "Baixar Arquivo da Financeira", "consultahistoricodocliente.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.15", "Consulta Hist&oacute;rico do Cliente", "consulta_u.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.16", "Estorno de Cart&atilde;o de Credito", "estornodecartaodecredito.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.17", "Consulta de T&iacute;tulo a Receber", "pesquisatitulo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.18", "Parcelamento Fatura", "parcelamentodefatura.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.19", "Retorno de Cargas", "retornocargas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.20", "Realoca&ccedil;&atilde;o de Carga", "realocaçãodecarga.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.21", "Exporta&ccedil;&atilde;o Arquivo Financeira", "formexpcontratofinanceira.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.22", "Localiza&ccedil;&atilde;o de T&iacute;tulos", "localizacaotitulos.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.23", "Envio para Cart&oacute;rio", "enviocartorio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.24", "Envio para Protesto", "envioprotesto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.25", "Estorno Envio Cart&oacute;rio", "estornoenviocartório.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.26", "Estorno Envio Protesto", "estornoenvioprotesto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.27", "Emite Nota Promissoria", "emitenotapromissoria.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.28", "Rel Duplicatas em Cartorio", "relduplcart.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.1.29", "Atribui&ccedil;&atilde;o de Responsabilidade", "atribresp.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2", "Contas a Pagar", "contasapagar.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.3.2.1", "Fatura a Pagar", "faturaapagar.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.2", "Provis&atilde;o de Fatura a Pagar", "provisaofaturaspagar.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.3", "Efetiva Provis&atilde;o de Fatura a Pagar", "efetivaprovisao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.4", "Pagamento de T&iacute;tulo", "pagamentodetitulo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.5", "Estorno de Titulo", "estornotitulo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.6", "Ficha Financeira do Fornecedor", "fichafinanceiradofornecedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.7", "Gera Cheque", "geracheque.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.8", "Imprime Cheque", "imprcheque.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.9", "Validar Titulo", "validar_titulo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.10", "Montar Border&ocirc; a Pagar", "borderotitulosapagar.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.11", "Liberar Border&ocirc; a Pagar", "liberarborderotitulosapagar.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.12", "Dados Boleto Fornecedor", "dadosboletofornecedor.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.13", "Libera&ccedil;&atilde;o de Pagamento de Comiss&atilde;o", "liberacaopagamentocomissao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.14", "Consulta de T&iacute;tulo a Pagar", "consultadetítuloapagar.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.15", "Pagamento de T&iacute;tulo por Border&ocirc;", "pagamentotitulocombordero.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.2.16", "Suspens&atilde;o de T&iacute;tulos a Pagar", "suspensaodetitulos.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.3", "Caixa", "caixa.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.3.3.1", "Movimento de Caixa", "movimentodecaixa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.3.2", "Transfere Saldo Caixa", "transferesaldocaixa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.3.3", "Relat&oacute;rios", "relatórios.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.3.3.3.1", "Posi&ccedil;&atilde;o Caixa e Banco", "posicaocaixabanco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.3.3.2", "Relat&oacute;rio Movimento Caixa", "relmovimentocaixa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.3.3.3", "Relat&oacute;rio Fechamento Caixa", "relatóriofechamentocaixa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.3.3.4", "Relatorio de Fechamento Caixa - Sangria", "relatoriodefechamentocaixa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.4", "Banco", "banco.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.3.4.1", "Movimento de Banco", "movimentodebanco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.4.2", "Digita&ccedil;&atilde;o do Extrato", "digitaçãodoextrato.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.4.3", "Concilia&ccedil;&atilde;o Banc&aacute;ria", "conciliaçãobancária.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.4.4", "Transfer&ecirc;ncia Entre Contas", "transferênciaentrecontas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.4.5", "Fechamento Di&aacute;rio Banco", "fechamentodiáriobanco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.4.6", "Montagem Border&ocirc; a Receber", "montagemborderôareceber.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.4.7", "Transfer&ecirc;ncia Banc&aacute;ria por TED ou DOC", "transferênciabancáriaported.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.4.8", "Empr&eacute;stimo Financeiro", "empréstimofinanceiro.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.4.9", "Relat&oacute;rios", "relatórios2.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.3.4.9.1", "Extrato Banc&aacute;rio", "extratobancário.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.4.9.2", "Relat&oacute;rio Movimento Banco", "relatóriomovimentobanco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.4.9.3", "Relatorio Fechamento Banc&aacute;rio", "relatoriofechamentobancário.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.5", "Malote", "malote.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.3.5.1", "Acerto de Malote", "acertodemalote.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.6", "Aplica&ccedil;&atilde;o Financeira", "aplicaçãofinanceira.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.3.6.1", "&Iacute;ndices de Aplica&ccedil;&atilde;o Financeira", "rendimentoaplicacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.6.2", "Simula&ccedil;&atilde;o de Aplica&ccedil;&atilde;o Financeira", "simulaaplicfinanceira.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.6.3", "Movimento de Aplica&ccedil;&atilde;o Financeira", "movimentoaplicacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.6.4", "Resgate da Aplica&ccedil;&atilde;o Financeira", "resgateaplicacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.7", "Negocia&ccedil;&atilde;o", "negociação.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("10.3.7.1", "Negocia&ccedil;&atilde;o de Diverg&ecirc;ncias", "negociacaodedivergencias.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("10.3.7.2", "Libera&ccedil;&atilde;o de Negocia&ccedil;&atilde;o de Diverg&ecirc;ncias", "liberanegociacaodedivergencia.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12", "Contabilidade e Or&ccedil;amento", "contabilidade.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("12.1", "Par&acirc;metros", "parâmetros.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("12.1.1", "Par&acirc;metro Cont&aacute;bil Unid.Empresarial", "parâmetrodecontabilidade.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.1.2", "Par&acirc;metro do Plano de Conta Padr&atilde;o", "parametroplanodeconta.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.1.3", "Par&acirc;metro do Centro de Custo", "parametrocentrodecusto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.1.4", "Par&acirc;metro Cont&aacute;bil Un.Empres por Fun&ccedil;&atilde;o", "parametrocontabilporfuncao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.2", "Manuten&ccedil;&atilde;o", "manutenção.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("12.2.1", "Plano de Conta Padr&atilde;o", "cadastroplanodecontaspadrao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.2.2", "Plano de Conta Empresa", "planoconta.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.2.3", "Hist&oacute;rico Cont&aacute;bil Padr&atilde;o", "cadashistcontpadrao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.2.4", "Lan&ccedil;amento Cont&aacute;bil Padr&atilde;o", "lançamentocontábilpadrão.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.2.5", "Centro de Custo", "centrocusto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.2.6", "Rateio por Centro de Custo", "rateioccusto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.2.7", "Grupo de Apura&ccedil;&atilde;o do Exerc&iacute;cio", "grupoapuracaocontab.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.2.8", "Grupo de Fechamento", "grupofechamentoscont.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.3", "Movimenta&ccedil;&atilde;o", "movimentação.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("12.3.1", "Or&ccedil;amento", "orcamentoccusto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.3.2", "Lan&ccedil;amento Cont&aacute;bil", "cadastrolancamentocontabil.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.3.3", "Fechamento M&ecirc;s", "fechamentomes.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.3.4", "Saldo Inicial do Plano de Contas", "saldoplanoconta.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.3.5", "Fechamento Grupo de Apura&ccedil;&atilde;o", "sequencia_help_74.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.4", "Relat&oacute;rios", "relatórios.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("12.4.1", "Raz&atilde;o", "razao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.4.2", "Di&aacute;rio", "diario.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.4.3", "Balancete", "balancete.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.4.4", "D.R.E  Demonstra&ccedil;&atilde;o Resultados Exerc&iacute;cio", "demostracaoderesultados.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.4.5", "Balan&ccedil;o Patrimonial", "balancopatrimonial.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.4.6", "Movimenta&ccedil;&atilde;o por Centro de Custo", "relcentrocusto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.4.7", "Resultado Econ&ocirc;mico", "ccustoresultado.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.4.8", "Termo de Abertura e Encerramento", "termo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.4.9", "Extrato Consolidado", "extratoconsolidado.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("12.5", "Ger&ecirc;ncia", "gerência.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("12.5.1", "Or&ccedil;ado vs Realizado", "orcadovsrealizado.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14", "Patrim&ocirc;nio", "patrimonio.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("14.1", "Par&acirc;metros", "parâmetros.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("14.1.1", "Par&acirc;metro por Unidade Empresarial", "parâmetrodepatrimonio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.2", "Manuten&ccedil;&atilde;o", "manutenção.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("14.2.1", "Grupo de Patrim&ocirc;nio", "grupopatrimonio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.2.2", "Tipo de Patrim&ocirc;nio", "tipodepatrimônio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.2.3", "Sub-Tipo de Patrim&ocirc;nio", "cadastrodesubtipodepatrimônio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.2.4", "Motivo da Baixa", "motivobaixa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.2.5", "Patrim&ocirc;nio", "cadastrodepatrimonio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.3", "Movimenta&ccedil;&atilde;o", "movimentação.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("14.3.1", "Deslocamento de Patrim&ocirc;nio", "deslocamentodepatrimônio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.3.2", "Transfer&ecirc;ncia de Patrim&ocirc;nio", "transferenciadepatrimonio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.3.3", "Baixa de Patrim&ocirc;nio", "baixadepatrimônio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.3.4", "Lan&ccedil;a Deprecia&ccedil;&atilde;o", "lançadepreciação.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.3.5", "Reavalia&ccedil;&atilde;o de Patrim&ocirc;nio", "reavaliaçãodepatrimônio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.3.6", "Garantia", "garantiapatrimonio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.3.7", "Invent&aacute;rio", "inventariodepatrimonio.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("14.3.7.1", "Registro de Invent&aacute;rio", "registrodepatrimônio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.3.7.2", "Planilha de Inventario", "planilhainventariopatrimonio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.3.7.3", "Contagem de Invent&aacute;rio", "contaginventario.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.3.7.4", "Divergencia Contagem", "divergenciacontagem.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.4", "Relat&oacute;rios", "relatórios.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("14.4.1", "Relat&oacute;rio de Patrim&ocirc;nios", "relatóriodepatrimônios.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.4.2", "Rel Termo de Responsabilidade", "reltermoderesponsabilidade.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.4.3", "Relat&oacute;rio de Deprecia&ccedil;&atilde;o de Patrimonio", "relatóriodedepreciaçãodepa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.4.4", "Relat&oacute;rio de Baixa", "relatóriodebaixa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("14.4.5", "Hist&oacute;rico de Movimenta&ccedil;&otilde;es do Patrim&ocirc;nio", "históricodemovimentaçõesdo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("16", "Distribui&ccedil;&atilde;o", "", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("16.1", "Manuten&ccedil;&atilde;o", "manutenção.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("16.1.1", "Colgate Palmolive", "colgatepalmolive.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("16.2", "Transmiss&atilde;o", "transmissão.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("16.2.1", "Colgate Palmolive", "transmcolgpalm.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("16.2.2", "Masterfoods", "transmissãomasterfoods.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("16.3", "Relat&oacute;rios", "relatórios.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("16.3.1", "Estoque e Venda de Produtos", "sequencia_help_13.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("16.3.2", "Acompanhamento de Vendas", "relacompvendas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("18", "Recursos Humanos", "", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("18.1", "Manuten&ccedil;&atilde;o", "manutenção.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("18.1.1", "Profiss&atilde;o", "profissao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("18.1.2", "Cargos e Fun&ccedil;&otilde;es", "cadastrodecargosefuncoes.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20", "Produ&ccedil;&atilde;o", "", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("20.1", "Par&acirc;metros", "parâmetros.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("20.1.1", "Par&acirc;metros de Produ&ccedil;&atilde;o", "param_producao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.2", "Manuten&ccedil;&atilde;o", "manutenção.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("20.2.1", "Etapa de Produ&ccedil;&atilde;o", "etapa_producao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.2.2", "Question&aacute;rio Produ&ccedil;&atilde;o", "questionario_producao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.2.3", "Classifica&ccedil;&atilde;o de Produ&ccedil;&atilde;o", "avaliacaodeproducaonaconfeccao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.2.4", "Pre&ccedil;o de Terceiro", "preco_lava_faccao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.2.5", "Controle Lavanderia", "controlelavanderia.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.2.6", "Modelo de Maquinas e Itens de Manuten&ccedil;&atilde;o", "modelomaquina.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.2.7", "Maquina de Produ&ccedil;&atilde;o", "maquinaproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.2.8", "Moldes", "molde.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.2.9", "Historico de Manuten&ccedil;&atilde;o", "historicomanutencao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.3", "Movimenta&ccedil;&atilde;o", "movimentação.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("20.3.1", "Requisi&ccedil;&atilde;o de Produ&ccedil;&atilde;o", "requisicaodeproducao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.3.2", "Entrada Lavanderia", "entrada_lavanderia.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.3.3", "Retornos de Produ&ccedil;&atilde;o", "retorno_producao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.3.4", "Lan&ccedil;amento Estoque Terceiro Tempor&aacute;rio", "sequencia_help_18.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.3.5", "Inicia e Finaliza Produ&ccedil;&atilde;o", "iniciaproducao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.4", "Relat&oacute;rios", "relatórios.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("20.4.1", "Estoques de Produto", "estoquesdeproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.4.2", "Estoques de Produto por Etapa", "estoquesdeprodutoporetapa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.4.3", "Composi&ccedil;&atilde;o de Produto", "relatoriocomposicaoproduto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.4.4", "Requisi&ccedil;&atilde;o por Produto", "relatorio_produto.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.4.5", "Produ&ccedil;&atilde;o por Etapa", "relatorio_etapa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.4.6", "Estoque em Terceiro", "estoque_terceiro.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.4.7", "Custo por Etapa", "estoqueetapapreco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.4.8", "Pre&ccedil;o Produto por Etapa", "precoprodutoetapa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.4.9", "Avalia&ccedil;&atilde;o de Produ&ccedil;&atilde;o", "rel_avaliacao_producao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("20.4.10", "Consumo de Manuten&ccedil;&atilde;o", "consumomanutencao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22", "Invent&aacute;rio", "", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("22.1", "Geral", "geral.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("22.1.1", "Controle de Invent&aacute;rio", "geracaoinventario.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.1.2", "Contagem Invent&aacute;rio", "contageminventário.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.1.3", "Recontagem Invent&aacute;rio", "recontageminventário.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.2", "Terceiro", "terceiro.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("22.2.1", "Gera&ccedil;&atilde;o Invent&aacute;rio Terceiro", "geraçãoinventárioterceiro.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.2.2", "Planilha de Produtos Terceiro", "planilhadeprodutosterceiro.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.2.3", "Digita&ccedil;&atilde;o Invent&aacute;rio Terceiro", "digitacaoinventarioterceiro.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.2.4", "Rel.Diverg.Estoque e Digita&ccedil;&atilde;o Terceiro", "sequencia_help_17.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.2.5", "Zerar Estoque Terceiro", "zerarestoqueterceiro.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.2.6", "Atualizar Estoque Terceiro", "atualizarestoqueterceiro.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.3", "Endere&ccedil;o", "endereço.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("22.3.1", "Gera&ccedil;&atilde;o", "inventarioporendereçogeração.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.3.2", "Planilha de Produtos", "sequencia_help_39.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.3.3", "Contagem de Produtos", "contageminventárioendereco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.3.4", "Recontagem de Produtos", "recontagemdeprodutos.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("22.3.5", "Atualizar Estoque", "atualizarestoqueendereco.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("24", "Fechamento", "", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("24.1", "Manuten&ccedil;&atilde;o Fechamento", "manutencaofechamento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("24.2", "Chamador Fechamento", "chamadorfechamento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("24.3", "Hist&oacute;rico Fechamento", "historicofechamento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("24.4", "Relat&oacute;rios", "relatórios.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("24.4.1", "Relat&oacute;rio de Fluxo de Caixa", "fluxocaixa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("24.4.2", "Resumo Geral da Empresa", "relresumogeraldaempresa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26", "Controle de Frota", "", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("26.1", "Par&acirc;metros", "parâmetros.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("26.1.1", "Par&acirc;metro de Frota por Fun&ccedil;&atilde;o", "parâmetrodefrotafunção.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.1.2", "Par&acirc;metro de Frota por Tipo de Ve&iacute;culo", "sequencia_help_28.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.2", "Manuten&ccedil;&atilde;o", "manutenção.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("26.2.1", "Tipo de Combust&iacute;vel", "tipodecombustível.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.2.2", "Acess&oacute;rios do Ve&iacute;culo", "acessóriosdoveículo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.2.3", "Tipo de Ve&iacute;culo", "tipodeveiculo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.2.4", "Item de Verifica&ccedil;&atilde;o", "cadastrodeitemdeverificação.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.2.5", "Grupo de Verifica&ccedil;&atilde;o", "cadastrodegrupodeverificação.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.2.6", "Pneus", "pneu.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.2.7", "Ve&iacute;culos", "cadastrodeveiculo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.2.8", "Seguro Ve&iacute;culo", "seguroveiculo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3", "Movimenta&ccedil;&atilde;o", "movimentação.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("26.3.1", "Lan&ccedil;amento de Sa&iacute;da de Ve&iacute;culo", "lançamentodesaídadeveículo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.2", "Lan&ccedil;amento de Entrada de Ve&iacute;culo", "lançamentodeentradadeveículo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.3", "Consulta Hist&oacute;rico de Ve&iacute;culo", "consultahistóricodeveículo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.4", "Ordem de Servi&ccedil;o", "ordemdeserviço.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.5", "Agendamento de Ordem Servi&ccedil;o", "agendamentodeordemserviço.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.6", "Vistoria de Ordem de Servi&ccedil;o", "vistoriadeordemdeserviço.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.7", "Renova&ccedil;&atilde;o de Frota", "renovaçãodefrota.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.8", "Controle de Pneus", "controledepneus.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.9", "Libera Ve&iacute;culo", "liberaveículo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.10", "Reparo Pneu", "reparopneu.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.11", "Controle de Abastecimento", "controledeabastecimento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.12", "Sa&iacute;da de Pe&ccedil;as/Ferramentas", "movimentoestoque.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.13", "Devolu&ccedil;&atilde;o Pe&ccedil;as/Ferramentas", "movimentoestoqueentrada.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.3.14", "Baixa de Requisi&ccedil;&otilde;es de Abastecimento", "sequencia_help_35.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.4", "Relat&oacute;rios", "relatórios.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("26.4.1", "Relat&oacute;rio de Ve&iacute;culos", "relatorioveiculo.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.4.2", "Relat&oacute;rio Grupo de Verifica&ccedil;&atilde;o", "relatoriogrupoverificacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.4.3", "Relat&oacute;rio Hist&oacute;rico Pneu", "relhistoricopneu.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.5", "Adiantamentos", "adiantamento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.6", "Controle de Frota", "controlefrota.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("26.7", "Manutencao de Ve&iacute;culos e Pneus", "historicomanutencao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28", "Sistema", "sistema.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("28.1", "Estrutura Empresarial", "estruturaempresarial.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("28.1.1", "Corpora&ccedil;&atilde;o", "cadastrodecorporacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.1.2", "Empresa", "cadastrodeempresa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.1.3", "Unidade Empresarial (Parceiro)", "cadastrodeparceiros.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.1.4", "Setor", "cadastrodesetor1.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.1.5", "&Aacute;rea", "cadastrodearea.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.1.6", "Tipo de Empresa", "tipoempresa.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.2", "Estrutura de Endere&ccedil;os", "estruturadeendereços.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("28.2.1", "Pa&iacute;s", "cadastrodepais.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.2.2", "Estado", "cadastrodeestado.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.2.3", "Cidade", "cadastrodecidade.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.2.4", "Bairro", "cadastrodebairro.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.2.5", "CEP", "cadastrodecep.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.3", "Cadastros Gerais", "cadastrosgerais.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("28.3.1", "Atividade Econ&ocirc;mica", "cadastrodecae.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.3.2", "Moeda e Indexadores", "cadastrodemoeda.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.3.3", "Condi&ccedil;&atilde;o de Pagamento", "cadastrodecondicaodepagamento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.3.4", "Tipo de Documento", "cadastrodotipododocumento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.3.5", "Ramo de Atividade", "ramo_atividade.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.3.6", "Calend&aacute;rio", "programacaocalendario.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.3.7", "Motivo de Devolu&ccedil;&atilde;o ou Cancelamento", "motivodevcancelamento.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.3.8", "Layout para Exporta&ccedil;&atilde;o", "layoutexportacaoreg.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.3.9", "Layout para Importa&ccedil;&atilde;o", "layoutparaimportação.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4", "Administra&ccedil;&atilde;o do Sistema", "administraçãodosistema.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("28.4.1", "Usu&aacute;rio", "cadastrodeusuario.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.2", "Altera&ccedil;&atilde;o de Senha", "alterasenhadousuario.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.3", "Grupos de Acesso", "cadastrodegrupodeacesso.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.4", "Programa", "programas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.5", "Terminal", "cadastrodeterminal.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.6", "Impressora", "cadastrodeimpressoras.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.7", "Modelo de Impressora", "cadastrodemodelosdeimpressroas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.8", "Mensagens do Banco de Dados", "mensagensdobancodedados.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.9", "LOG de Usu&aacute;rio", "consultadelog´sdeusuário.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.10", "Controle de Numera&ccedil;&atilde;o", "controlenumero.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.11", "Importa&ccedil;&atilde;o de Dados", "importaçãodedados.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.12", "Correio", "mensagensdecorreio.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.13", "WorkFlow", "cadastrodeworkflow.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.14", "Fechamento Autom&aacute;tico", "fechamentoautomatico.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.4.15", "Par&acirc;metros do Sistema", "paramsistema.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.5", "Aplicativos", "aplicativos.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("28.5.1", "Importa&ccedil;&atilde;o C&oacute;digo Cliente", "imporparceiro.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.5.2", "Construtor de Pesquisas", "construtordepesquisas.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.5.3", "Construtor de Procedures", "geracaodeprocedures.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.5.4", "Construtor de Menus", "projetosdemenus.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.5.5", "Exp/Imp de Proc/Func/Trigg", "exportaimportapft.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.5.6", "Gerar Arquivo de Exporta&ccedil;&atilde;o", "geraarquivodeexportacao.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.5.7", "Importa&ccedil;&atilde;o de Arquivos", "importarqs.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.5.8", "Construtor de Relat&oacute;rios", "geradorderelatórios.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.5.9", "Exp/Imp de Layouts de Relat&oacute;rio", "aplicativoexpimplayouts.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.6", "Relat&oacute;rio", "relatório.htm", "", "cicon1.gif", "cicon2.gif");
tocTab[ir++] = new Array ("28.6.1", "Relat&oacute;rio de Cadastro de Parceiro", "relatoriodecadastrodeparceiro.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.6.2", "Etiqueta Cadastro de Cliente 2 Colunas", "emissãodeetiquetaporcliente.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.6.3", "Cart&atilde;o de Fidelidade/Etiqueta do Cliente", "cartaofidelidadecliente.htm", "", "cicon9.gif", "cicon9.gif");
tocTab[ir++] = new Array ("28.6.4", "Etiqueta do Funcion&aacute;rio", "etiquetafuncionario.htm", "", "cicon9.gif", "cicon9.gif");
isContent = true,
isIndex = false,
showNumbers = false,
tocBehaviour = new Array(1,1),
tocScroll=false,
tocLinks = new Array(0,0);
var oldOnError = null;
var isDyn = navigator.userAgent.toLowerCase().indexOf("opera") == -1;
var isIE = navigator.appName.toLowerCase().indexOf("explorer") > -1;
var oldCurrentNumber = "", oldLastVisitNumber = "";
var toDisplay = new Array();
for (ir=0; ir<tocTab.length; ir++) {
toDisplay[ir] = tocTab[ir][0].split(".").length==1;
}
function windowErr() {
isDyn = false;
$hmtoc.location.href = "horus_content.htm";
window.onerror = oldOnError;
}
function reDisplay(currentNumber,tocChange,noLink,e) {
if (isIndex && ($hmtoc.location.href.substring($hmtoc.location.href.lastIndexOf("/")+1,$hmtoc.location.href.length) != "horus_kwindex.htm")) { isIndex=false; isContent=true; }
if (currentNumber == "navIndex") { isContent=false; }
if (currentNumber == "navContent") { isIndex=false; isContent=true; }
if (e) {
ctrlKeyDown = (isIE) ? e.ctrlKey : (e.modifiers==2);
if (tocChange && ctrlKeyDown) tocChange = 2;
}
var currentNumArray = currentNumber.split(".");
var currentLevel = currentNumArray.length-1;
var currentIndex = 0;
var currentHash = "";
if ((currentNumber == "") && (top.location.href.lastIndexOf("?") > 0)) {
currentNumber = top.location.href.substring(top.location.href.lastIndexOf("?")+1,top.location.href.length);
if (currentNumber.lastIndexOf(",") > 0) {
currentHash = "#" + currentNumber.substring(currentNumber.lastIndexOf(",")+1, currentNumber.length);
currentNumber = currentNumber.substring(0, currentNumber.lastIndexOf(","));
}
}
for (i=0; i<tocTab.length; i++) {
if ((tocTab[i][0] == currentNumber) || (tocTab[i][2] == currentNumber && tocTab[i][2] != "")) {
currentIndex = i;
currentNumber = tocTab[i][0];
currentNumArray = currentNumber.split(".");
currentLevel = currentNumArray.length-1;
break;
}
}
if (currentIndex < tocTab.length-1) {
nextLevel = tocTab[currentIndex+1][0].split(".").length-1;
currentIsExpanded = nextLevel > currentLevel && toDisplay[currentIndex+1];
}
else currentIsExpanded = false;
theHref = (noLink) ? "" : tocTab[currentIndex][2] + currentHash;
theTarget = tocTab[currentIndex][3];
for (i=1; i<tocTab.length; i++) {
if (tocChange) {
thisNumber = tocTab[i][0];
thisNumArray = thisNumber.split(".");
thisLevel = thisNumArray.length-1;
isOnPath = true;
if (thisLevel > 0) {
for (j=0; j<thisLevel; j++) {
isOnPath = (j>currentLevel) ? false : isOnPath && (thisNumArray[j] == currentNumArray[j]);
}
}
toDisplay[i] = (tocChange == 1) ? isOnPath : (isOnPath || toDisplay[i]);
if (thisNumber.indexOf(currentNumber+".")==0 && thisLevel > currentLevel) {
if (currentIsExpanded) toDisplay[i] = false;
else toDisplay[i] = (thisLevel == currentLevel+1);
}
}
}
if (!isContent && !isIndex) {
$hmtoc.location.href = "horus_kwindex.htm";
isIndex = true;
}
hasSelection = false;
if (isContent) {
if (!isDyn) {
if ($hmtoc.location.href.substring($hmtoc.location.href.lastIndexOf("/")+1,$hmtoc.location.href.length) != "horus_content.htm") $hmtoc.location.href = "horus_content.htm";
}
else {
oldOnError = window.onerror;
window.onerror = windowErr;
$hmtoc.document.clear();
$hmtoc.document.write("<html>\n\r<head></head>\n\r<style type=\"text/css\">\n\r       SPAN.heading1 { font-family: Arial,Helvetica; font-weight: normal; font-size: 10pt; color: #000000; text-decoration: none }\n\r       SPAN.heading2 { font-family: Arial,Helvetica; font-weight: normal; font-size: 9pt; color: #000000; text-decoration: none }\n\r       SPAN.heading3 { font-family: Arial,Helvetica; font-weight: normal; font-size: 8pt; color: #000000; text-decoration: none }\n\r       SPAN.heading4 { font-family: Arial,Helvetica; font-weight: normal; font-size: 8pt; color: #000000; text-decoration: none }\n\r       SPAN.heading5 { font-family: Arial,Helvetica; font-weight: normal; font-size: 8pt; color: #000000; text-decoration: none }\n\r       SPAN.heading6 { font-family: Arial,Helvetica; font-weight: normal; font-size: 8pt; color: #000000; text-decoration: none }\n\r\n\r       SPAN.hilight1 { font-family: Arial,Helvetica; font-weight: normal; font-size: 10pt; color: #FFFFFF; background: #002682; text-decoration: none }\n\r       SPAN.hilight2 { font-family: Arial,Helvetica; font-weight: normal; font-size: 9pt; color: #FFFFFF; background: #002682; text-decoration: none }\n\r       SPAN.hilight3 { font-family: Arial,Helvetica; font-weight: normal; font-size: 8pt; color: #FFFFFF; background: #002682; text-decoration: none }\n\r       SPAN.hilight4 { font-family: Arial,Helvetica; font-weight: normal; font-size: 8pt; color: #FFFFFF; background: #002682; text-decoration: none }\n\r       SPAN.hilight5 { font-family: Arial,Helvetica; font-weight: normal; font-size: 8pt; color: #FFFFFF; background: #002682; text-decoration: none }\n\r       SPAN.hilight6 { font-family: Arial,Helvetica; font-weight: normal; font-size: 8pt; color: #FFFFFF; background: #002682; text-decoration: none }\n\r</style>\n\r<body bgcolor=\"#FFFFFF\">\n\r<font face=\"Arial,Helvetica\" size=\"4\"><b>Horus</b></font><br>\n\r<font face=\"Arial,Helvetica\" size=\"2\">\n\r<a href=\"javaScript:parent.reDisplay(\'navIndex\',0,0);\">Keyword Index</a>\n\r</font><br><br><br>\n\r\n\r  <!-- Place holder for the TOC, do not delete the line below -->\n\r  ");
for (i=0; i<tocTab.length; i++) {
if (toDisplay[i]) {
thisNumber = tocTab[i][0];
thisNumArray = thisNumber.split(".");
thisLevel = thisNumArray.length-1;
isCurrent = (i == currentIndex);
if (i < tocTab.length-1) {
nextLevel = tocTab[i+1][0].split(".").length-1;
img = (thisLevel >= nextLevel) ? tocTab[i][4] : ((toDisplay[i+1]) ? tocTab[i][5] : tocTab[i][4]);
}
else img = tocTab[i][4];
thisTextClass = ((thisNumber==currentNumber)?("hilight"):("heading"));
thisNode = ((thisNumber==currentNumber)?("<div id=currentNode></div>"):(""));
if (thisNumber==currentNumber) hasSelection = true;
$hmtoc.document.write(thisNode);
$hmtoc.document.write("<table border=0 cellspacing=0 cellpadding=2>");
if (img!="") {
$hmtoc.document.write("<tr><td width=" + ((thisLevel+1) * 20) + " align=right valign=top>");
$hmtoc.document.write("<a href=\"javaScript:history.go(0)\" onMouseDown=\"parent.reDisplay('" + thisNumber + "'," + tocBehaviour[0] + "," + tocLinks[0] + ",event)\">");
$hmtoc.document.write("<img src=\"" + img + "\" border=0></a>");
}
else $hmtoc.document.write("<tr><td width=" + (thisLevel * 20) + " align=right valign=top>");
$hmtoc.document.write("</td><td align=left>");
$hmtoc.document.write("<a href=\"javaScript:history.go(0)\" onMouseDown=\"parent.reDisplay('" + thisNumber + "'," + tocBehaviour[1] + "," + tocLinks[1] + ",event)\">");
$hmtoc.document.write("<span class=\""  + thisTextClass + ((thisLevel>5) ? 6 : thisLevel+1) + "\">");
$hmtoc.document.write( ((showNumbers)?(thisNumber+" "):"") + tocTab[i][1]);
$hmtoc.document.write("</span></a>");
$hmtoc.document.writeln("</td></tr></table>");
window.onerror = oldOnError;
} //isDyn
} //isContent
}
}
if (!noLink) {
oldLastVisitNumber = oldCurrentNumber;
oldCurrentNumber = currentNumber;
}
if (isContent && isDyn) {
$hmtoc.document.write("\n\r\n\r<hr><font face=\"Arial,Helvetica\" size=\"1\">Copyright&copy; 2000-2006 VMSet Sistemas. Todos os direitos reservados</font>\n\r</body>\n\r</html>\n\r");
$hmtoc.document.close();
}
if (theHref)
if (theTarget=="top") top.location.href = theHref;
else if (theTarget=="parent") parent.location.href = theHref;
else if (theTarget=="blank") open(theHref,"");
else {
$hmcontent.location.href = theHref;
if ((tocScroll) && (hasSelection)) $hmtoc.document.all["currentNode"].scrollIntoView();
}
}
