titles = new Array("Abastecimento de Lojas",
	"Abastecimento do Deposito",
	"Aceite de Título",
	"Acerto de Carga",
	"Acerto de Estoque",
	"Acerto de Malote",
	"Acertos de Estoque",
	"Acessórios do Veículo",
	"Acompanhamento de Pedidos por Atendente",
	"Acompanhamento de Metas de Venda",
	"Acompanhamento de Metas de Venda",
	"Acompanhamento Diário de Vendas",
	"Acompanhamento Diário de Vendas",
	"Acompanhamento de Metas",
	"Acompanhamento de Venda Futura/Encomenda",
	"Adiantamentos",
	"AdministradoraFinanceira",
	"Administração do Sistema",
	"Administração de Preços",
	"AgenciaBancaria",
	"Agendamento de Ordem Serviço",
	"Ajuste de Precos / MarkUp",
	"Ajuste de Preço Coletivo",
	"Ajuste de Preço Exceção Produto",
	"Alocacão de Produto em Palete",
	"Alocação",
	"Alocação Produto",
	"Altera Dados do Produto",
	"Altera Estoque Regulador",
	"Altera Fabricante Produto",
	"Altera Fabricante Produto",
	"Ajuste de Preço por Subcategoria(Kilo)",
	"Alterar Valor Digitado Pedido de Venda",
	"Alterar Valor Digitado Pedido de Venda",
	"Alteração de Senha",
	"Altera Sub-Categoria de Produto",
	"Altera Sub-Categoria de Produto",
	"Alteração Comissões por Nível Desconto",
	"Alteração de Comissões do Vendedor",
	"Alteração de Comissões do Vendedor",
	"AlteraçãodePedido",
	"Alteração de Senha",
	"Alteração do Vendedor do Pedido",
	"Altera Vendedor de Cliente",
	"Aplicação",
	"Exp/Imp de Layouts de Relatório",
	"Aplicativos",
	"Aplicação Financeira",
	"Apresentação",
	"Atendimento de Venda por Encomenda",
	"Atendimento de Venda por Encomenda",
	"Atendimento Parcial de Pedido de Venda",
	"Atribuição de Responsabilidade",
	"Atualização do Estoque",
	"Atualizar Estoque",
	"Atualizar Estoque Terceiro",
	"Atualizar Preco de Tabela",
	"Preço de Custo / Venda",
	"Atualiza Tabela de Preço",
	"Atualiza Tabela de Preço Vigente",
	"Critica e Atualização de VFE",
	"Autorização Venda Convênio",
	"Classificação de Produção",
	"Baixa de Patrimônio",
	"Balancete",
	"Balanço Patrimonial",
	"Balanço Patrimonial",
	"Banco",
	"Bonificação",
	"Montar Borderô a Pagar",
	"BOTOES",
	"Botões",
	"Botões2",
	"Histórico Contábil Padrão",
	"Situação do Produto",
	"Unidade de Produto",
	"Área",
	"Região Área de Venda",
	"Bairro",
	"Banco",
	"Atividade Econômica",
	"Caixa",
	"Cargos e Funções",
	"Categoria de Produto",
	"CEP",
	"Cidade",
	"Comprador",
	"Condição de Pagamento",
	"Conta Corrente",
	"Cadastro de Cores",
	"Cadastro de Cores do Fabricante",
	"Corporação",
	"Departamento de Produto",
	"Cadastro de Embalagem de Compra",
	"Empresa",
	"Estado",
	"Folhas de Cheque",
	"Grupos de Acesso",
	"Grupo de Verificação",
	"Histórico Contábil Padrão",
	"Impressora",
	"Item de Verificação",
	"Cadastro de Marcas",
	"Modelo de Impressora",
	"Moeda e Indexadores",
	"País",
	"Parâmetros de Estoque",
	"Unidade Empresarial (Parceiro)",
	"Patrimônio",
	"Cadastro de Referencia Lote",
	"Região de Preço de Venda",
	"Região de Preço de Venda",
	"Seção de Produto",
	"Setor",
	"Subcategoria de Produto",
	"Sub-Tipo de Patrimônio",
	"Supervisor de Vendas",
	"Terminal",
	"Usuário",
	"Veículos",
	"WorkFlow",
	"Caixa",
	"Parâmetros de Compra",
	"Tipo de Movimentação",
	"Tipo de Documento",
	"Lançamento Contábil",
	"Plano de Conta Padrão",
	"Plano de Conta Padrão",
	"Cadastros Gerais",
	"Cancelamento de Devolução de Compras",
	"Cancelamento NF Saida",
	"Cancelamento de Devolução de Venda",
	"Cancela Nota Fiscal",
	"Confirma Cancelamento da NF Caixa",
	"Confirma Cancelamento de NF Expedição",
	"Cancelar Entrada de Mercadoria",
	"Cartão de Fidelidade/Etiqueta do Cliente",
	"Cartão",
	"Categoria",
	"Categoria de Produto",
	"Resultado Econômico",
	"Centro de Custo",
	"Certificado",
	"Certificado",
	"Chamador Fechamento",
	"Cheques",
	"ChequesaPrazo",
	"Classificação Aplicação",
	"Cliente",
	"Cliente2",
	"Clientes Distribuição",
	"Clientes por Carga",
	"Clientes por Vendedor",
	"CobradorEntregador",
	"Entregador/Cobrador",
	"Colgate Palmolive",
	"Comissao Supervisor/Vendedor/Cliente",
	"Comissão Transportadora",
	"Comissão por Promotor",
	"Comissão de Vendas",
	"Comissões por Faturamento",
	"Comissões por Recebimento",
	"ComportamentoPopularidade",
	"Comprador",
	"Compras",
	"Comprovante Venda Futura Imediata",
	"Comprovante Venda Futura Imediata",
	"Conciliação Bancária",
	"Concorrente",
	"Taxas Cond. Pagto por Administradora",
	"Condição de Pagto no Fabricante",
	"Condição de pagamento Por SubCategoria",
	"Conferente",
	"Relatório de Conferente de Cargas",
	"Conferente",
	"Conhecimento de Frete",
	"Conhecimento de Frete",
	"Consignação de Carga em Aberto",
	"Retorno de Consignação Cliente",
	"Construtor de Pesquisas",
	"Consultas",
	"Consulta Automotiva",
	"LOG de Usuário",
	"Consulta de Notas Fiscais",
	"Consulta de Título a Pagar",
	"Consulta Histórico do Cliente",
	"Consulta Histórico de Veículo",
	"Consulta Imobiliária",
	"Consulta Itens por Fornecedor",
	"Consulta Notas Fiscais",
	"Consulta Pedido de Compra",
	"Consulta Preços de Venda",
	"Consulta Preços por Cond Pgto",
	"Consulta produto",
	"Consulta Requisição de Compra",
	"Consultas",
	"Consulta Saldo de Estoque",
	"Consulta Tabela de Fornecedor",
	"Consulta Tabela de Precos",
	"Consulta Histórico do Cliente",
	"Consumo de Manutenção",
	"Contabilidade e Orçamento",
	"Contador",
	"Contador2",
	"Contagem Inventário",
	"Contagem de Produtos",
	"Contagem de Inventário",
	"Contas a Pagar",
	"Contas a Receber",
	"Contas Correntes dos Vendedores",
	"Contrato de Compra",
	"ContratoFinanceiro",
	"Contrato de Financeiras",
	"Controle de Abastecimento",
	"Controle de Entregas",
	"Controle de Numeração",
	"Controle de Pneus",
	"Controle de Frota",
	"Controle Lavanderia",
	"Controle de Numeração",
	"Cadastro de Cores",
	"Cadastro de Cores do Fabricante",
	"Cores Tintas Automotivas",
	"Cores Tintas Imobiliárias",
	"Correio",
	"Cotação de Produto",
	"Curva ABC",
	"Dados Boleto Fornecedor",
	"D.R.E Demonstração Resultados Exercício",
	"Departamento",
	"Departamento de Produto",
	"Deslocamento de Patrimônio",
	"Devolução de Compra",
	"Devolução de Compra por Ordem Cega",
	"Devolução de Compra",
	"Devolução de Compra por Ordem Cega",
	"Devolução de Mercadorias",
	"Diário",
	"Digitação Inventário Terceiro",
	"Digitação do Extrato",
	"Contagem Inventário",
	"Divergencia Contagem",
	"Diário",
	"D.R.E  Demonstração Resultados Exercício",
	"Efetiva Provisão de Fatura a Pagar",
	"Efetiva Provisão de Fatura a Receber",
	"Cadastro de Embalagem de Compra",
	"Emissão do Livro de Preço",
	"Etiqueta Produto",
	"Etiqueta Cadastro de Cliente 2 Colunas",
	"Emite Nota Promissoria",
	"Empréstimo Financeiro",
	"Endereço",
	"Entrada Cega",
	"Entrada de Mercadoria",
	"Entrada de Mercadorias",
	"Entrada de Mercadorias por Período",
	"Entrada/Saída de Estoque Manual",
	"Entrada/Saída de Estoque Manual",
	"Entrada Lavanderia",
	"Entrada de Mercadoria",
	"Entregas",
	"Envio para Cartório",
	"Envio para Protesto",
	"Espelho do Pedido",
	"Estoque",
	"Estoque Desconto Adicional",
	"Custo por Etapa",
	"Estoque Financeiro por Fornecedor",
	"Estoques de Produto",
	"Estoques de Produto por Etapa",
	"Estoque em Terceiro",
	"Estorno Atendimento Parcial Pedido Venda",
	"Estorno de Cartão de Credito",
	"Estorno Envio Cartório",
	"Estorno Envio Protesto",
	"Estornos da Devolução Venda",
	"Estorno de Titulo",
	"Estorno de Titulo",
	"Produtos Vendidos de Outras Unidade Empr",
	"Estrutura de Endereços",
	"Estrutura Empresarial",
	"Etapa de Produção",
	"Etiqueta do Funcionário",
	"Etiqueta Produto",
	"Etiqueta dos Produtos para Despacho",
	"Etiqueta dos Produtos da Nota Fiscal",
	"Exp/Imp de Proc/Func/Trigg",
	"Extrato Bancário",
	"Extrato Consolidado",
	"Fabricante",
	"Fatura a Pagar",
	"Fatura a Receber",
	"Fechamento Automático",
	"Fechamento Automático",
	"Fechamento Diário Banco",
	"Fechamento Grupo de Apuração",
	"Fechamento Mês",
	"Fechamento Mês",
	"Ficha de Estoque de Produto",
	"Ficha Financeira",
	"Ficha Financeira do Fornecedor",
	"Filtro de Propriedade por Palete",
	"Finalização",
	"Financeiro",
	"Relatório de Fluxo de Caixa",
	"Fonte de Informação Rendimento Aplicação",
	"Geraçao Força de Vendas",
	"Geraçao Força Vendas Agrovicultor",
	"Geração Força de Vendas Blink",
	"Geração Força de Vendas Kraft",
	"Força de Vendas Next Solution",
	"Exportação Arquivo Financeira",
	"Fornecedor",
	"Fornecedor2",
	"Funcionario",
	"Garantia",
	"Gerar Arquivo de Exportação",
	"Gera Arquivo SCI/Equifax",
	"Construtor de Procedures",
	"Controle de Inventário",
	"Geração Inventário Terceiro",
	"Geração Nota Fiscal Expedição Individual",
	"Geração Nota Fiscal Expedição Individual",
	"Geração Nota Fiscal Atacado",
	"Geração Nota Fiscal Varejo",
	"Gera Cheque",
	"Construtor de Relatórios",
	"Geral",
	"Gerar Livro Preço",
	"Gera Nota Fiscal",
	"Emissão de Nota Fiscal a partir do Cupom",
	"Geração Nota Fiscal Venda Futura",
	"Gera Nota Fiscal",
	"Gerar Ordem Cega",
	"Gerar Ordem Cega",
	"Gera Senha para Entrada de Mercadorias",
	"Gera Tabela de Preço Auxiliar",
	"Geração Inventário Terceiro",
	"Gerência",
	"Gerência",
	"Grupo de Apuração do Exercício",
	"Grupo de Apuração do Exercício",
	"Grupo de Preço",
	"Grupo de Preço",
	"Grupo de Fechamento",
	"Grupo de Fechamento",
	"Grupo de Patrimônio",
	"Grupos de Acesso",
	"Similares ou Idênticos",
	"Grupo Similar ou Idêntico",
	"Histórico Fechamento",
	"Historico de Manutenção",
	"Historico por produto",
	"Historico por produto",
	"Histórico de Movimentações do Patrimônio",
	"Histórico Liberação de Pedido Compra",
	"Horus",
	"No title",
	"Importação Código Cliente",
	"Importaçao Força de Vendas",
	"Importação Força de Vendas Next Solution",
	"Importação de Arquivos",
	"Importação de Dados",
	"Importação Força de Vendas Blink",
	"Imprime Cheque",
	"Impressão de Documentos da Carga",
	"Impressão de Documentos da Carga",
	"Impressora",
	"Impressão de Mapas não Impressos",
	"Impressão de Mapas não Impressos",
	"Indenização",
	"InformaçãoMovimentoCusto2",
	"Informações",
	"Inicia e Finaliza Produção",
	"Instrução Banco",
	"Inventário",
	"Geração",
	"Itens no Estoque por Categoria",
	"Lançamento",
	"Lançar Nota Fiscal",
	"Lancar Ordem Cega",
	"Lancar Ordem Cega",
	"Lança Depreciação",
	"Lançamento",
	"Lançamento Contábil",
	"Lançamento Contábil Padrão",
	"Lançamento de Entrada de Veículo",
	"Lançamento de Saída de Veículo",
	"Lançar Nota Fiscal",
	"Layout para Exportação",
	"Layout para Importação",
	"Libera Cliente p/Desconto Adicional",
	"Liberação de Pagamento de Comissão",
	"Histórico Liberação de Pedido Compra",
	"Liberação de Pedido de Venda",
	"Liberação de Negociação de Divergências",
	"Liberação de Pedido de Compra",
	"Liberar Borderô a Pagar",
	"Libera Veículo",
	"Liberação de Pedido de Compra",
	"Linhas",
	"Listagem de Pedidos Liberados",
	"Localização de Títulos",
	"LOG de Usuário",
	"Logística",
	"Malote",
	"Manutenção Fechamento",
	"Manutencao",
	"Alínea Cheque Devolvido",
	"Manutenção",
	"Gerente de Venda",
	"Gerente de Venda",
	"Motivo para Lançamento do Conhecimento",
	"Motivo para Lançamento do Conhecimento",
	"Manutenção",
	"Manutenção",
	"Manutenção",
	"Manutenção",
	"Manutenção",
	"Manutenção",
	"Manutenção",
	"Manutenção",
	"Manutenção",
	"Manutenção",
	"Manutenção",
	"Mapa de Abastecimento Ponto de Apanho",
	"Mapa de Alocacao de Produtos / Setor",
	"Mapa de Separacao",
	"Mapa de Separação por Carga",
	"Mapa de Separacao",
	"Mapa de Separacao",
	"Maquina de Produção",
	"Cadastro de Marcas",
	"Margem de Lucro por Produto",
	"Mensagem produto na Nota Fiscal",
	"Mensagem produto na Nota Fiscal",
	"Correio",
	"Mensagens do Banco de Dados",
	"Meta de Vendas",
	"Meta de Vendas Semanal",
	"Objetivos de Vendas Semanal por Vendedor",
	"Meta de Roteirização",
	"Minuta de Despacho",
	"Minuta de Despacho",
	"Modelo de Impressora",
	"Modelo de Maquinas e Itens de Manutenção",
	"Moldes",
	"Montadoras",
	"Montagem Borderô a Receber",
	"Montagem de Carga",
	"Montagem de Cargas",
	"Motivo da Baixa",
	"Motivo de Devolução ou Cancelamento",
	"Movimentação Conta Corrente Vendedores",
	"Movimentacao",
	"Movimentação",
	"Movimentação por Centro de Custo",
	"Movimentação",
	"Movimentação",
	"Movimentação",
	"Movimentação",
	"Movimentação",
	"Movimentação",
	"Movimentação",
	"Movimentação",
	"Movimentação",
	"Movimento de Aplicação Financeira",
	"MovimentoCarroForte",
	"Movimento de Banco",
	"Movimento de Caixa",
	"Saída de Peças/Ferramentas",
	"Devolução Peças/Ferramentas",
	"Notas Fiscais para Transportadoras",
	"Negociação de Divergências",
	"Negociação",
	"Impressão de Notas Fiscais não Impressas",
	"Norma de Paletização",
	"Relatório de Notas sem Minuta",
	"Reemissão de Nota Fiscal",
	"Tipo de Ocorrencia",
	"Orçado vs Realizado",
	"Orçamento",
	"Orçamento de Compra / Mês",
	"Ordem de pagamento a fornecedor",
	"Ordem de pagamento a fornecedor",
	"Ordem de Serviço",
	"Orçado vs Realizado",
	"Orçamento",
	"Orçamento de Compra / Mês",
	"Outras Entradas",
	"Outras Saídas",
	"Pagamento de Título",
	"Pagamento de Título por Borderô",
	"Parâmetros de Cliente",
	"Parâmetro do Centro de Custo",
	"Parâmetro Contábil Un.Empres por Função",
	"Parâmetros de Compra por Função",
	"Parâmetro do Plano de Conta Padrão",
	"Parametros",
	"Parâmetros da Corporação",
	"Parâmetros de Fornecedor",
	"Parâmetros de Venda",
	"Parâmetros de Venda por Função",
	"Parâmetros de EDI",
	"Parâmetros Malote",
	"Parâmetros Preço de Venda",
	"Parametros",
	"Parâmetros Unidade Empresarial Função",
	"Parâmetros",
	"Parâmetros",
	"Parâmetros Unidade Empresarial",
	"Parâmetros de Produto",
	"Parâmetros do Sistema",
	"Parâmetros de Produção",
	"Parâmetros da Transportadora",
	"Parcelamento Fatura",
	"Parcelamento de Título",
	"Parâmetro Contábil Unid.Empresarial",
	"Parâmetro de Frota por Função",
	"Parâmetro por Unidade Empresarial",
	"Parâmetros",
	"Parâmetros de Auto Serviço",
	"Parâmetros de Compra",
	"Parâmetros de Compra por Função",
	"Parâmetros de Estoque",
	"Parâmetros de Fornecedor",
	"Parâmetros de Produto",
	"Parâmetros do Sistema",
	"Parâmetros",
	"Parâmetros",
	"Parâmetros",
	"Parâmetros",
	"Parametros",
	"Parâmetros",
	"Parâmetros",
	"Parâmetros",
	"Patrimônio",
	"Pedido",
	"Pedido",
	"Pedido Adicional Wacco",
	"Pedido Bonificação Expedição Individual",
	"Pedido de Compra",
	"PedidodeCompra2",
	"Pedido de Compra",
	"Pedido de Compra - Sintético",
	"Pedido de Compra - Bonificação",
	"Pedido de Compra - Sintético",
	"Pedido de Bonificação Cliente Balcão",
	"Pedido de Bonificação Cliente Balcão",
	"Pedido de Bonificação Cliente Televendas",
	"Pedido de Consignação de Cliente",
	"Pedido de Venda Televendas",
	"Pedidos de Entregas / Retirada",
	"PedidosGerados",
	"Pedido de Venda Balcão",
	"Pedido de Venda Compacto",
	"Pedido de Venda Expedição Individual",
	"Pedido de Venda Expedição Individual",
	"Pedido Adicional",
	"Consulta de Título a Receber",
	"PessoaFísica",
	"PessoaJurídica",
	"Planilha de Produtos",
	"Planilha de Produtos Terceiro",
	"Planilha de Inventario",
	"Plano de Conta Empresa",
	"Plano de Conta Empresa",
	"Pneus",
	"Posição Caixa e Banco",
	"Posicao de Estoque",
	"Posicao de Estoque",
	"Relatório de Preço Médio Vendido",
	"Preço Produto por Etapa",
	"Preço Concorrente",
	"Preço de Terceiro",
	"Preço de Tabela de Fornecedor",
	"Premiação de Representantes",
	"Preço Concorrente",
	"PreçodeCusto(3)",
	"PreçodeTabela(4)",
	"Preço de Tabela de Fornecedor",
	"PreçoOferta(2)",
	"Processa Estoque",
	"Processa Estoque",
	"Consulta Produtos na Carga",
	"Produto",
	"Produto",
	"Relatório Produtos Lote Máximo",
	"Produtos cortados pelo Rateio de Carga",
	"Produtos em Garantia (Troca)",
	"Produto sem Preço de Venda",
	"Produtos Vendidos",
	"Produtos Vendidos",
	"Produtos em Garantia (Troca)",
	"Profissão",
	"Programa",
	"Calendário",
	"Programa",
	"Construtor de Menus",
	"Projeção de Vendas",
	"Campanha de Vendas",
	"PromotorDegustador",
	"Propriedade de Armazenamento",
	"Provisão de Fatura a Pagar",
	"Provisao de Faturas a receber",
	"Questionário Produção",
	"Ramo de Atividade",
	"Rateio de Carga",
	"Rateio por Centro de Custo",
	"Razão",
	"Razão",
	"Realocação de Carga",
	"Reavaliação de Patrimônio",
	"Recebimento de Cartão de Credito",
	"Recebimento Títulos",
	"Recontagem de Produtos",
	"Recontagem Inventário",
	"Reemissão de Etiqueta de Alocação",
	"Reemissão de Mapa de Separação",
	"Reemissão de Pedido de Compra",
	"Cadastro de Referencia Lote",
	"Registro de Inventário",
	"Relatório de Acerto de Estoque",
	"Acompanhamento de Vendas",
	"Análise de Clientes",
	"Composição de Produto",
	"Conferencia Recontagem",
	"Relatório de Cadastro de Parceiro",
	"Relatorio de Clientes Inativos",
	"Comissões por Nivel de Desconto",
	"Relatório de Comissões por Recebimento",
	"Relatório de Entrega - Venda Atacado",
	"Relatorio de Fechamento Caixa - Sangria",
	"Relatorio de Giro de Estoque",
	"Relatório de Itens por Fornecedor",
	"Mix por Área",
	"Relatório de Saldo de Estoque",
	"Relatório de Venda por Itens",
	"Comissao Entregador",
	"Relatorio Fechamento Bancário",
	"Vendas Geral por Fabricante",
	"Relatório Grupo de Verificação",
	"Relação de Meta de Vendas",
	"Relatorios",
	"Relatório de Sugestão de Compra - Unibom",
	"Relatório de Veículos",
	"Vendas/Indenização",
	"Produção por Etapa",
	"Relatório de Fechamento de Caixa Varejo",
	"Relatórios de Indenização",
	"Requisição por Produto",
	"Relatorio Resultado de Vendas",
	"Relatório",
	"Relatório de Acerto de Estoque",
	"Relatório de Baixa",
	"Relatório de Bonificação",
	"Relatório de Cotação por Período",
	"Relatório de Depreciação de Patrimonio",
	"Desempenho de Vendas",
	"Relatório de Estoque Excedente",
	"Relatório de Estoque Mínimo",
	"Relatório de Fretes por Período",
	"Relatório de Fretes por Período",
	"Relatório de Indenização no Estoque",
	"Relatório de Itens por Fornecedor",
	"Relatório de Itens sem Entrada",
	"Relatório de Itens Sem Giro",
	"Linha de Produto por RCA/Margem",
	"Linha de Produto por Cidade",
	"Linha de Produto por RCA",
	"Relatório de Patrimônios",
	"Relatório de Pedido de Compra",
	"Relatório de Pedidos de Compra Wacco",
	"Relatório de Preços (Concorrência)",
	"Relatório de Produtos Conjuntos",
	"Relatório de Saldo de Estoque",
	"Relatório de Sugestão Compra/Calendário",
	"Relatório de Sugestão de Compra",
	"Relatório de Sugestão de Compra - Unibom",
	"Relatório de Sugestão de Compra Champiom",
	"Relatório de Sugestão de Compras Wacco",
	"Relatório de Sugestão de Compras Teles",
	"Relatório de Sugestão de Compras Suporte",
	"Relatório Fechamento Caixa",
	"Relatório Movimento Banco",
	"Relatório Produtos Lote Máximo",
	"Relatórios",
	"Relatórios",
	"Relatórios",
	"Relatórios",
	"Relatórios Administrativos",
	"Relatório de Produtos Conjuntos",
	"Relatórios",
	"Relatórios",
	"Relatórios",
	"Relatórios",
	"Relatórios",
	"Relatórios",
	"Relatórios",
	"Relatórios",
	"Relatórios",
	"Relatórios",
	"Relatório",
	"Relatórios",
	"Relação de Pedidos a Liberar",
	"Relação de Pedidos Reservados",
	"Relatório de Cargas Pendentes",
	"Movimentação por Centro de Custo",
	"Clientes por Regiao/Status",
	"Relatório de Cotação por Período",
	"Rel Duplicatas em Cartorio",
	"Relatório de Estoque Excedente",
	"Relatório Histórico Pneu",
	"Relatório de Itens sem Entrada",
	"Relatório de Itens Sem Giro",
	"Lista de Preços por Período",
	"Relatório de Meta de Vendas Semanal",
	"Relatório de Montagem de Cargas",
	"Movimentação Conta Corrente Vendedores",
	"Relatório Movimento Caixa",
	"Relação de Notas Fiscais",
	"Pedidos de Venda",
	"Relatório de Pedidos de Venda (Completo)",
	"Pedidos a Faturar por Fabricante",
	"Pedidos por Vendedor",
	"Pedidos por Vendedor (Wacco)",
	"Resumo Geral da Empresa",
	"Relatório de Seguro de Cargas",
	"Relatório de Sugestão de Compra",
	"Rel Termo de Responsabilidade",
	"Venda e Devolução por Fabricante",
	"Resumo das Vendas por Forma de Pagamento",
	"Avaliação de Produção",
	"Relatório de Preços (Concorrência)",
	"Relatório de Indenização no Estoque",
	"Itens no Estoque por Categoria",
	"Índices de Aplicação Financeira",
	"Renegociação de Titulo",
	"Renovação de Frota",
	"Reparo Pneu",
	"Representante",
	"Requisição de Produção",
	"Requisição de Compra",
	"Resgate da Aplicação Financeira",
	"Resultado Econômico",
	"Resumo Comissões por Nível de Desconto",
	"ResumodeMalote",
	"Resumo de Pedidos a Faturar por Vendedor",
	"Resumo Vendas Empresa",
	"Resumo de Faturamento por Vendedor",
	"Retorno de Cargas",
	"Retorno de Venda fora do Estabelecimento",
	"Retornos de Produção",
	"Romaneio de Cargas",
	"Rota de Entrega",
	"Rota de Venda",
	"Roteirização",
	"Saldo Inicial do Plano de Contas",
	"Saldo Inicial do Plano de Contas",
	"Seguro Veículo",
	"SelfColor",
	"Gera Senha para Entrada de Mercadorias",
	"Sepervisor",
	"Estoque e Venda de Produtos",
	"Rel.Diverg.Estoque e Digitação Terceiro",
	"Lançamento Estoque Terceiro Temporário",
	"Atendimento Parcial de Pedido de Venda",
	"Pedido de Consignação de Cliente",
	"Relatório de Sugestão Compra/Calendário",
	"Parâmetro de Frota por Tipo de Veículo",
	"Cancelamento de Devolução de Compras",
	"Relatório de Pedidos de Compra Wacco",
	"Relatório de Sugestão de Compras Wacco",
	"Baixa de Requisições de Abastecimento",
	"Estorno Atendimento Parcial Pedido Venda",
	"Abastecimento do Deposito",
	"Planilha de Produtos",
	"Divergência Estoque/Recontagem por Setor",
	"Alteração de Preço por Grupo de Preço",
	"Relatório de Sugestão de Compras Teles",
	"Relatório de Sugestão de Compras Suporte",
	"Estoque Desconto Adicional",
	"Entrada de Mercadorias por Período",
	"Fechamento Grupo de Apuração",
	"Altera Dados do Produto",
	"Seção",
	"Seção de Produto",
	"Similares ou Idênticos",
	"Simulação de Aplicação Financeira",
	"Sistema",
	"Situaçãodoproduto(5)",
	"Situação do Produto",
	"Troca Situação do Produto",
	"SubCategoria",
	"Subcategoria de Produto",
	"SubRegião Área de Venda",
	"Requisição de Compra",
	"Suspensão de Títulos a Pagar",
	"Suspensão Venda para Contagem",
	"Suspensão Venda para Contagem",
	"Tabela de Preço",
	"Terceiro",
	"TerceironaProdução",
	"TerceironaProdução2",
	"Terminal",
	"Termo de Abertura e Encerramento",
	"Termo de Abertura e Encerramento",
	"Territórios de Venda",
	"Tipo de Combustível",
	"Tipo de Movimentação",
	"Tipo de Patrimônio",
	"Tipo de Veículo",
	"Tipo de Empresa",
	"TitulosRecebimento",
	"Tipo Entrega",
	"Tradutor",
	"Transferencia de Dados",
	"Transferência de Patrimônio",
	"Transferência EDI",
	"Transfere Saldo Caixa",
	"Transferência Bancária por TED ou DOC",
	"Transferência Entre Contas",
	"Colgate Palmolive",
	"Transmissão",
	"Masterfoods",
	"Transportadora",
	"Troca de Mercadorias",
	"Troca de Mercadorias",
	"Troca Situação do Produto",
	"TítulosaPagar",
	"TítulosaVencer",
	"TítulosemAberto",
	"TítulosPagamento",
	"TítulosVencidos",
	"Unidade de Produto",
	"UnidadeEmpresarial",
	"Usuário",
	"Vales",
	"Validar Titulo",
	"Venda",
	"Venda Atacado",
	"Melhores Clientes p/ Período",
	"Vendas por Embalagem de Movimentação",
	"Geração de NF de Venda Especial",
	"Venda Fora do Estabelecimento",
	"Gera NF Saida p/ Transito de Mercadoria",
	"Vendas",
	"Relatório Vendas Intervalo Produto",
	"Vendas X Recebimento",
	"Vendedor",
	"Vendedor2",
	"Vendedor",
	"Relatorio de Vendas por Unidade Produto",
	"Vistoria de Ordem de Serviço",
	"WorkFlow",
	"Zerar Estoque Terceiro",
	"Zerar o Estoque",
	"Alteração de Preço por Grupo de Preço",
	"Exp/Imp de Layouts de Relatório",
	"Classificação de Produção",
	"Baixar Arquivo da Financeira",
	"Baixa de Requisições de Abastecimento",
	"Situação do Produto",
	"CNAE - Fiscal",
	"Condição de Pagamento",
	"Grupo de Verificação",
	"Substituição de ICMS",
	"Item de Verificação",
	"Mensagens do Banco de Dados",
	"Modelo de Impressora",
	"Parâmetros de Estoque",
	"Sub-Tipo de Patrimônio",
	"Tributação Fiscal",
	"Parâmetros de Compra",
	"Tipo de Movimentação",
	"Cancelamento de Devolução de Compras",
	"Carta de Correção de Nota Fiscal",
	"Conciliação Bancária",
	"Consulta Preços de Venda",
	"Consulta Preços por Cond Pgto",
	"Contagem Inventário",
	"Controle de Inventário",
	"Extrato Bancário",
	"Devolução de Compra por Ordem Cega",
	"Fonte de Informação Rendimento Aplicação",
	"Digitação do Extrato",
	"Divergencia Contagem",
	"Etiqueta Cadastro de Cliente 2 Colunas",
	"Empréstimo Financeiro",
	"Entrada/Saída de Estoque Manual",
	"Exceções de Tributação Fiscal na Entrada",
	"Exceções de Tributação Fiscal na Saída",
	"Exp/Imp de Proc/Func/Trigg",
	"Geração de Arquivo de Notas Fiscais",
	"Gera Sintegra",
	"Fechamento Grupo de Apuração",
	"Fechamento Diário Banco",
	"Geração Força de Vendas Blink",
	"Importação Força de Vendas Blink",
	"Gera Contabilidade",
	"Importação do Sintegra",
	"Geração",
	"Planilha de Produtos",
	"Lançamento Estoque Terceiro Temporário",
	"Lançamento de Entrada de Veículo",
	"Manutenção do Livro Fiscal",
	"Layout para Exportação",
	"Manutenção",
	"Montagem Borderô a Receber",
	"Motivo de Devolução ou Cancelamento",
	"Movimentação",
	"Natureza de Operação",
	"Natureza de Operação por Movimento",
	"Nota Fiscal Complementar",
	"Outros valores",
	"Transferência Bancária por TED ou DOC",
	"Parâmetros Unidade Empresarial Função",
	"Parâmetro de Frota por Tipo de Veículo",
	"Planilha de Inventario",
	"Calendário",
	"Recontagem Inventário",
	"Redução de ICMS",
	"Refazer Livro Fiscal",
	"Apuração de ICMS",
	"Apuração de IPI",
	"Livro Registro de Entradas/Saídas",
	"Abastecimento do Deposito",
	"Departamento",
	"Relatório de Cadastro de Parceiro",
	"Produto",
	"Grupo Similar ou Idêntico",
	"Relatório de Itens por Fornecedor",
	"Entrada de Mercadorias por Período",
	"Estoque Desconto Adicional",
	"Relatorio Fechamento Bancário",
	"Relatório Movimento Banco",
	"Relatório de Sugestão de Compra - Unibom",
	"Estoque e Venda de Produtos",
	"Relatório de Sugestão de Compras Wacco",
	"Relatório de Sugestão de Compras Teles",
	"Relatório de Sugestão de Compras Suporte",
	"Relatório de Produtos Conjuntos",
	"Relatórios",
	"Relatórios de ISS",
	"Rel.Diverg.Estoque e Digitação Terceiro",
	"Sintegra",
	"Suframa",
	"Transferência Entre Contas",
	"Tributação por Estado");